name: Build Proxify

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Build for Android
      run: |
        mkdir -p builds
        GOOS=android GOARCH=arm64 go build -o builds/proxify-android-arm64
        GOOS=android GOARCH=arm go build -o builds/proxify-android-arm
        # Создаем архив для удобства скачивания
        cd builds
        tar czf proxify-android-builds.tar.gz proxify-android-*
        echo "Builds completed and archived in proxify-android-builds.tar.gz"
        # Выводим размер и содержимое для проверки
        ls -lh
        sha256sum proxify-android-builds.tar.gz
