name: Build Proxify

on: 
  workflow_dispatch:  # Это позволит запускать вручную из интерфейса

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        
    - name: Build for Android ARM64
      run: |
        GOOS=android GOARCH=arm64 go build -o proxify-android-arm64
        
    - name: Build for Android ARM
      run: |
        GOOS=android GOARCH=arm go build -o proxify-android-arm
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: proxify-binaries
        path: |
          proxify-android-arm64
          proxify-android-arm
