name: Build Proxify

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Нужно для создания релизов
      packages: write
      actions: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Build for Android
      run: |
        mkdir -p builds
        GOOS=android GOARCH=arm64 go build -o builds/proxify-android-arm64
        GOOS=android GOARCH=arm go build -o builds/proxify-android-arm
        cd builds
        tar czf proxify-android-builds.tar.gz proxify-android-*
        sha256sum proxify-android-builds.tar.gz > SHA256SUMS.txt
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: proxify-android-binaries
        path: builds/
        retention-days: 5

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v0.0.${{ github.run_number }}
        name: Release ${{ github.run_number }}
        draft: false
        prerelease: false
        files: |
          builds/proxify-android-builds.tar.gz
          builds/SHA256SUMS.txt
        body: |
          Automated release from GitHub Actions
          
          Contains:
          - Android ARM64 binary
          - Android ARM binary
          
          SHA256 checksums included in SHA256SUMS.txt
